### ISSUE TITLE
How can we store historical data with SQLite efficiently?

### ISSUE THREAD

**Issue by snehasi** [mahi397/LITGproject#6]
- https://softwareengineering.stackexchange.com/questions/156220/ways-to-have-a-history-of-changes-of-database-entries

- https://stackoverflow.com/questions/42477570/what-is-the-correct-database-structure-to-store-historical-data

Other options:
https://www.influxdata.com/

**Comment by mahi397** [comment]
- SQLite to be used
https://medium.com/@neslinesli93/how-to-efficiently-store-and-query-time-series-data-90313ff0ec20

- TODO: Create login database

**Comment by mahi397** [comment]
What exactly do we need a login database for? What will it contain?

**Comment by snehasi** [comment]
This will be a members only app - so we need an auth system, saved state of their app instance with previous entries for moods.
For a start, in the authentication system:
user_id (can be the Primary key)
Instead of the DB admin having access to the pwd, let's store a hash of the password(SHA 2 or 3):
`hash = hashing_func(pwd)` -> store this
We can also add a password salt.
When authenticating:
`entry_hash = hashing_func(entry_pass)`
`if(entry_hash == stored_hash):
#validate the login`

**Comment by snehasi** [comment]
Ways we can do this 7302448aa80a62189b1dada31b08add38ea53042
We store this hashed pwd in the db and check it later for auth

**Comment by mahi397** [comment]
> This will be a members only app - so we need an auth system, saved state of their app instance with previous entries for moods.
> For a start, in the authentication system:
> user_id (can be the Primary key)
> Instead of the DB admin having access to the pwd, let's store a hash of the password(SHA 2 or 3):
> `hash = hashing_func(pwd)` -> store this
> We can also add a password salt.
> When authenticating:
> `entry_hash = hashing_func(entry_pass)`
> `if(entry_hash == stored_hash): #validate the login`

So for the login/logout and authentication I made as part of a previous task, the DB admin had access to the password and the authentication was Django's own auth system, right? Now with this are we overriding that?
Also, to implement this, do I make a sqlite database containing UserID as PKey and other details like data, time and mood/activity?

**Comment by snehasi** [comment]
In this task, the goal was to find out if we could use Django's default db SQLite to store historical data or shift to another db.
> https://medium.com/@neslinesli93/how-to-efficiently-store-and-query-time-series-data-90313ff0ec20

Let's stick to SQLite - we can create model fields for moods before and after an activity and query with Django [ORM](https://tutorial.djangogirls.org/en/django_orm/#filter-objects)

Django's auth system will do the hashing, the admin doesn't have access to passwords, can only see their hashes. We can encrypt moods and activities data in the db.

> Also, to implement this, do I make a sqlite database containing UserID as PKey and other details like data, time and mood/activity?

The db is configured in settings.py [here](https://github.com/mahi397/LITGproject/blob/7302448aa80a62189b1dada31b08add38ea53042/project/mysite/settings.py#L80). I've opened #7 to next create db Models
